server:
  port: 6996

spring:
  jackson.default-property-inclusion: NON_NULL
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/market?createDatabaseIfNotExist=true
    username: root
    password: root
    data: classpath:/data/sql/prod-data.sql
    sql-script-encoding: UTF-8
    initialization-mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:none}
    password: ${EMAIL_PASSWORD:none}
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: secret-key